<?php 
//.............. Database Connection...................
$dir = 'sqlite:sqlite/task.sqlite'; //............. Sqlite DB Path..................
$conn = new PDO($dir); //.............. PDO Driver Connection.................
if(!$conn)
{
	die('Database Error');
}